import PrimaryButton from '@/components/buttons/primaryButton';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Banglar Math',
  description: 'Generated by create next app',
};
export default function Home() {
  return (
    <main className='flex min-h-screen flex-col items-center justify-between p-24'>
      <PrimaryButton text={'Login'} />
    </main>
  );
}
